### ISSUE TITLE
version numbers don't match

### ISSUE THREAD

**Issue by core-code** [tobeycarman/QLNetcdf#2]
i've downloaded version 0.0.3 from GitHub but after download it claims to already be at version 1.0 / 1

the CFBundleShortVersionString and CFBundleVersion entries in the Info.plist doesn't line-up with the release version

<img width="262" alt="Screenshot 2020-10-29 at 11 38 09" src="https://user-images.githubusercontent.com/1261954/97557613-49b40980-19db-11eb-89ab-022de3facf70.png">
<img width="306" alt="Screenshot 2020-10-29 at 11 38 35" src="https://user-images.githubusercontent.com/1261954/97557635-50428100-19db-11eb-842a-ac3698d417c7.png">

**Comment by tobeycarman** [comment]
Hmm, ok. I haven't touched this project in a quite a while, but can try to look at it at some point. I am happy to accept a pull request too if you are able to fix it.

**Comment by core-code** [comment]
thanks there. i've sent the pull request but these values will need to be changed before the next release.

**Comment by tobeycarman** [comment]
@core-code, I merged your PR, but as you noted, will need to change the values before next release. I am presently struggling to get the project to build and run in recent Xcode (11.3). I actually can build fine, but am having problems debugging. I think it is an SIP problem. If you have any experience with debugging QuickLook Plugins, I would be glad for any pointers.

**Comment by core-code** [comment]
> I merged your PR

thanks :)

> any experience with debugging QuickLook Plugins

sorry there. i looked at the QuickLook Plugins API very briefly once but it seemed more trouble than it is worth so i moved on...

**Comment by tobeycarman** [comment]
OK thanks. Yeah, it seems like the API and the code signing/security architecture has changed quite a bit since I first made QLNetcdf, so my old project isn't working. Oh well. Maybe someday I will get to it.
